# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/transposition.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


class Ui_Transposition(object):
    def setupUi(self, Transposition):
        Transposition.setObjectName("Transposition")
        Transposition.resize(716, 499)
        self.textEdit_2 = QtWidgets.QTextEdit(Transposition)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 280, 421, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(Transposition)
        self.label_4.setGeometry(QtCore.QRect(210, 20, 371, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Transposition)
        self.label.setGeometry(QtCore.QRect(70, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Transposition)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 450, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Transposition)
        self.label_2.setGeometry(QtCore.QRect(100, 200, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Transposition)
        self.lineEdit.setGeometry(QtCore.QRect(170, 210, 421, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(Transposition)
        self.textEdit.setGeometry(QtCore.QRect(170, 100, 421, 87))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Transposition)
        self.pushButton.setGeometry(QtCore.QRect(150, 440, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Transposition)
        self.label_3.setGeometry(QtCore.QRect(60, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Transposition)
        QtCore.QMetaObject.connectSlotsByName(Transposition)

    def retranslateUi(self, Transposition):
        _translate = QtCore.QCoreApplication.translate
        Transposition.setWindowTitle(_translate("Transposition", "Dialog"))
        self.label_4.setText(_translate("Transposition", "TRANSPOSITION CIPHER"))
        self.label.setText(_translate("Transposition", "Plain Text"))
        self.pushButton_2.setText(_translate("Transposition", "Decrypt"))
        self.label_2.setText(_translate("Transposition", "Key"))
        self.pushButton.setText(_translate("Transposition", "Encrypt"))
        self.label_3.setText(_translate("Transposition", "Cipher Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Transposition = QtWidgets.QDialog()
    ui = Ui_Transposition()
    ui.setupUi(Transposition)
    Transposition.show()
    sys.exit(app.exec_())
